name: Release Go Binary

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        run: |
          go build -ldflags "-X main.version=${{ github.ref_name }}" -o hubfly-storage ./cmd/hubfly-storage

      - name: Package zip
        run: |
          zip hubfly-storage-linux-amd64.zip hubfly-storage

      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            ./hubfly-storage-linux-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
